spring.application.name=DigitalAuthenticationSystem

spring.datasource.url=jdbc:mysql://localhost:3306/digital_authentication?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=digitalauthenticationsystem.das@gmail.com
spring.mail.password=kdpjwssabcwdjzqf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio SMS Configuration
twilio.account_sid=ACe372aa640a362be8d83e1f67f6e04d20
twilio.auth_token=15c32e26ec34abf6d6915b890f8f5616
twilio.phone_number=+16615146272

#Port
server.port=8080